// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-_lUik_3UrIhUzuX3Cqn8M0Kjd02uFn8',
    appId: '1:521244528275:android:1e851f29e6ac1740498766',
    messagingSenderId: '521244528275',
    projectId: 'mockcrack',
    storageBucket: 'mockcrack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCySRvqofqQ0qoDkWDimux1jO16VefMYuI',
    appId: '1:521244528275:ios:b1fad07e465c66b5498766',
    messagingSenderId: '521244528275',
    projectId: 'mockcrack',
    storageBucket: 'mockcrack.firebasestorage.app',
    iosBundleId: 'com.example.mockcrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOa1PRjIalfe8tfPlpkBfa5nu9exikRjk',
    appId: '1:521244528275:web:9184868da91c82af498766',
    messagingSenderId: '521244528275',
    projectId: 'mockcrack',
    authDomain: 'mockcrack.firebaseapp.com',
    storageBucket: 'mockcrack.firebasestorage.app',
    measurementId: 'G-67VGKLG2TS',
  );
}
